# Site settings
title: Newbie Software Development
header-img: img/home-bg.png
email: zindzi.thompson@gmail.com
copyright_name: vitivey
description: > # this means to ignore newlines until "baseurl:"
  1-2-3
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  vitivey
learn_profile: vitivey
email_username: zindzi.thompson@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
